version: "3"
services:
  redis:
    image: redis:6.2.4
    ports:
      - "16379:6379"
    volumes:
      - /tmp/docker:/tmp
    environment:
      PROFILE: local
  mysql:
    image: mysql:5.7.34
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswd"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqluserpasswd"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "test"

  rabbitmq:
    image: rabbitmq:3.8.17-rc.1-management
    ports:
      - "15673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: local-lollipop
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmqpasswd
